from django.urls import path
from .views import (
    index,
    dashboard,
    manage_products,
    add_product_view,
    view_product_view,
    delete_product,
    update_product_view,
    give_rating_view,
    product_detail_page,
    supplier_profile,
    cart_view,
    update_cart_view,
    checkout_view,
    add_order_address,
    change_order_address,
    update_cart_item_quantity,
    delete_item_from_cart,
    all_products_view,
    process_order,
    order_received,
    your_orders,
    manage_order,
    mark_order_item_complete
)
urlpatterns = [
    path('', index, name="supplier_index"),
    path('dashboard/', dashboard, name='dashboard'),
    path('manage_products/', manage_products, name="manage_products"),
    path('add_product/', add_product_view, name="add_product"),
    path('view_products/', view_product_view, name="view_products"),
    path('delete_product/<str:pk>/', delete_product, name="delete_product"),
    path('update_product/<str:pk>/', update_product_view, name="update_product"),
    path('give_rating/<str:pk>/', give_rating_view, name='give_rating'),
    path('product_detail/<str:product_id>/', product_detail_page, name='product_detail_page'),
    path('supplier_profile/<str:supplier_id>/', supplier_profile, name='supplier_profile'),
    path('cart/', cart_view, name='cart'),
    path('update_cart/', update_cart_view, name='update_cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('add_order_address/', add_order_address, name='add_order_address'),
    path('change_order_address/', change_order_address, name='change_order_address'),
    path('update_cart_item_quantity/', update_cart_item_quantity, name='update_cart_item_quantity'),
    path('delete_item_from_cart/', delete_item_from_cart, name='delete_item_from_cart'),
    path('all_products_view/', all_products_view, name='all_products'),
    path('process_order/', process_order, name='process_order'),
    path('order_received/', order_received, name="order_received"),
    path('your_orders/', your_orders, name='your_orders'),
    path('manage_order/<str:item_id>/', manage_order, name='manage_order'),
    path('mark_order_item_complete/', mark_order_item_complete, name='mark_order_item_complete')
]