# Generated by Django 4.0.3 on 2022-05-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_orderitem_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_status',
            new_name='order_complete_status',
        ),
    ]
