# Generated by Django 4.0.3 on 2022-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_product_percent_discount_over_bulk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Garments', 'Garments'), ('Cosmetics', 'Cosmetics'), ('Electronics', 'Electronics'), ('Stationery', 'Stationery'), ('Musical', 'Musical'), ('Pharmacy', 'Pharmacy'), ('Furniture', 'Furniture'), ('Sports', 'Sports')], max_length=11),
        ),
    ]
